// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CloseSessionReducer from "../close_session_reducer";
import LeaveSessionReducer from "../leave_session_reducer";
import OpenSessionReducer from "../open_session_reducer";
import PublishSnapshotReducer from "../publish_snapshot_reducer";
import RequestJoinReducer from "../request_join_reducer";
import SendInputReducer from "../send_input_reducer";
import UpdateSessionReducer from "../update_session_reducer";

export type CloseSessionParams = __Infer<typeof CloseSessionReducer>;
export type LeaveSessionParams = __Infer<typeof LeaveSessionReducer>;
export type OpenSessionParams = __Infer<typeof OpenSessionReducer>;
export type PublishSnapshotParams = __Infer<typeof PublishSnapshotReducer>;
export type RequestJoinParams = __Infer<typeof RequestJoinReducer>;
export type SendInputParams = __Infer<typeof SendInputReducer>;
export type UpdateSessionParams = __Infer<typeof UpdateSessionReducer>;

